import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";
import { readFileSync, cpSync, renameSync, rmSync, existsSync } from "fs";

// Read canister IDs from root .env (generated by dfx deploy)
function loadCanisterEnv(): Record<string, string> {
  const defines: Record<string, string> = {};
  try {
    const envPath = path.resolve(__dirname, "../../.env");
    const content = readFileSync(envPath, "utf-8");
    for (const line of content.split("\n")) {
      const match = line.match(/^(CANISTER_\w+|DFX_\w+|DEV_\w+)=(.*)$/);
      if (match) {
        defines[`import.meta.env.${match[1]}`] = JSON.stringify(match[2]);
      }
    }
  } catch {
    // .env may not exist yet — canister IDs will be empty
  }
  return defines;
}

/**
 * Post-build plugin: flattens nested HTML output and copies extension assets.
 * Vite outputs HTML relative to project root, e.g. dist/src/sidepanel/sidepanel.html.
 * This moves them to dist/sidepanel.html and dist/tab.html, then copies
 * manifest.json and public/ assets (callback.html, icons/) into dist/.
 */
function extensionPostBuild(): Plugin {
  return {
    name: "extension-post-build",
    closeBundle() {
      const dist = path.resolve(__dirname, "dist");

      // Flatten HTML files: dist/src/sidepanel/sidepanel.html → dist/sidepanel.html
      const moves: [string, string][] = [
        [path.join(dist, "src/sidepanel/sidepanel.html"), path.join(dist, "sidepanel.html")],
        [path.join(dist, "src/tab/tab.html"), path.join(dist, "tab.html")],
      ];
      for (const [from, to] of moves) {
        if (existsSync(from)) {
          renameSync(from, to);
        }
      }
      // Clean up empty nested dirs
      rmSync(path.join(dist, "src"), { recursive: true, force: true });

      // Copy manifest.json
      cpSync(path.resolve(__dirname, "manifest.json"), path.join(dist, "manifest.json"));

      // Copy public/ assets (callback.html, icons/) — skip isomorphic symlink
      const publicDir = path.resolve(__dirname, "public");
      cpSync(path.join(publicDir, "callback.html"), path.join(dist, "callback.html"));
      cpSync(path.join(publicDir, "sandbox.html"), path.join(dist, "sandbox.html"));
      if (existsSync(path.join(publicDir, "icons"))) {
        cpSync(path.join(publicDir, "icons"), path.join(dist, "icons"), { recursive: true });
      }

      // Copy isomorphic SmartClient runtime (follow symlink, copy real files)
      const isoSrc = path.join(publicDir, "isomorphic");
      const isoDst = path.join(dist, "isomorphic");
      if (existsSync(isoSrc) && !existsSync(isoDst)) {
        cpSync(isoSrc, isoDst, { recursive: true, dereference: true });
      }
    },
  };
}

export default defineConfig({
  define: {
    global: "globalThis",
    "process.env": {},
    ...loadCanisterEnv(),
  },
  plugins: [react(), extensionPostBuild()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "../frontend/src"),
      "@ext": path.resolve(__dirname, "src"),
    },
  },
  publicDir: false, // We handle public/ copying in the post-build plugin
  build: {
    outDir: "dist",
    emptyOutDir: true,
    rollupOptions: {
      input: {
        sidepanel: path.resolve(__dirname, "src/sidepanel/sidepanel.html"),
        tab: path.resolve(__dirname, "src/tab/tab.html"),
        "service-worker": path.resolve(__dirname, "src/background/service-worker.ts"),
      },
      output: {
        entryFileNames: "[name].js",
        chunkFileNames: "chunks/[name]-[hash].js",
        assetFileNames: "assets/[name]-[hash][extname]",
      },
    },
  },
});
